FROM python:3.9-alpine
# WORKDIR /gateway
ENV FLASK_APP=gateway/app.py
ENV FLASK_RUN_HOST=0.0.0.0
COPY gateway/requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN apk add sqlite
EXPOSE 5000
COPY . .
CMD ["python", "gateway/app.py"]
RUN cd ..
