FROM python:3.9-alpine
WORKDIR /gateway
COPY /gateway /gateway
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
# COPY gateway/requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN apk add sqlite
EXPOSE 5000
CMD ["python", "app.py"]
