FROM python:3.9-alpine
WORKDIR /home
RUN pwd
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
COPY apartments apartments
RUN ls
WORKDIR /apartments
RUN ls
RUN pip install -r requirements.txt
RUN apk add sqlite
EXPOSE 5000
# COPY . .
CMD ["python", "app.py"]

