FROM python:3.9-alpine
WORKDIR /home
RUN ls
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
# COPY requirements.txt requirements.txt
COPY apartments/requirements.txt requirements.txt # FOR IMAGE CREATION!!!
RUN pip install -r requirements.txt
RUN apk add sqlite
EXPOSE 5000
COPY . .
CMD ["python", "app.py"]
