FROM python:3.9-alpine
WORKDIR /search
COPY /search /search
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN pip install -r requirements.txt
RUN apk add sqlite
EXPOSE 5000
CMD ["python", "app.py"]
