FROM python:3.9-alpine
WORKDIR /reserve
COPY /reserve /reserve
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
# COPY reserve/requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN apk add sqlite
EXPOSE 5000
# COPY . .
CMD ["python", "app.py"]
# WORKDIR ..
