name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub Registry
      run: echo ${{DOCKERHUB_PASSWORD}} | docker login -u ${{DOCKERHUB_USERNAME}} --password-stdin
      
    - name: Build the Apartments Docker image
      run: docker build . --file apartments/dockerfile --tag apartments:$(date +%s)
      
    - name: Build the Gateway Docker image
      run: docker build . --file gateway/dockerfile --tag gateway:$(date +%s)
    
    - name: Push the latest Docker image
      run: docker push janakaras/gateway:$(date +%s)
      
    - name: Build the Reserve Docker image
      run: docker build . --file reserve/dockerfile --tag reserve:$(date +%s)
      
    - name: Build the Search Docker image
      run: docker build . --file search/dockerfile --tag search:$(date +%s)
