name: Image Create & Push to Dockerhub

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub Registry
      run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      
    - name: Build the Apartments Docker image
      run: docker build --file apartments/dockerfile_image --tag janakaras/apartments:latest .
      
    - name: Build the Gateway Docker image
      run: docker build --file gateway/dockerfile_image --tag janakaras/gateway:latest .
      
    - name: Build the Reserve Docker image
      run: docker build --file reserve/dockerfile_image --tag janakaras/reserve:latest .
      
    - name: Build the Search Docker image
      run: docker build --file search/dockerfile_image --tag janakaras/search:latest .
      
    - name: Push the Apartments Docker image
      run: docker push janakaras/apartments:latest
      
    - name: Push the Gateway Docker image
      run: docker push janakaras/gateway:latest
      
    - name: Push the Reserve Docker image
      run: docker push janakaras/reserve:latest
      
    - name: Push the Search Docker image
      run: docker push janakaras/search:latest
