name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub Registry
      run: echo Programmieren20222 | docker login -u janakaras --password-stdin
      
    - name: Build the Apartments Docker image
      run: docker build . --file apartments/Dockerfile --tag apartments:$(date +%s)
      
    - name: Build the Gateway Docker image
      run: docker build ./gateway --file Dockerfile --tag gateway:$(date +%s)
      
    - name: Build the Reserve Docker image
      run: docker build ./reverse --file Dockerfile --tag reserve:$(date +%s)
      
    - name: Build the Search Docker image
      run: docker build ./search --file Dockerfile --tag search:$(date +%s)
