name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub Registry
      run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      
    - name: Build the Apartments Docker image
      run: cd apartments | docker build . --file dockerfile --tag janakaras/apartments:latest | cd ..
      
    - name: Build the Gateway Docker image
      run: cd gateway | docker build . --file dockerfile --tag janakaras/gateway:latest | cd ..
      
    - name: Build the Reserve Docker image
      run: cd reserve | docker build . --file dockerfile --tag janakaras/reserve:latest | cd ..
      
    - name: Build the Search Docker image
      run: cd search | docker build . --file dockerfile --tag janakaras/search:latest | cd ..
      
    - name: Push the Apartments Docker image
      run: docker push janakaras/apartments:latest
      
    - name: Push the Gateway Docker image
      run: docker push janakaras/gateway:latest
      
    - name: Push the Reserve Docker image
      run: docker push janakaras/reserve:latest
      
    - name: Push the Search Docker image
      run: docker push janakaras/search:latest
