
name: 'EC2 .zip-based Update'

on:
 workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
 
    - name: SSH to EC2 and Update
      run: |
        echo "${{ secrets.CC_UNI }}" | tr -d '\r' > key.pem | chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@54.80.67.161 '
          sudo service docker start &&
          sudo rm -rf * &&
          sudo wget https://github.com/janakaras/docker-in-the-cloud/archive/refs/heads/main.zip &&
          sudo unzip main.zip &&
          cd docker-in-the-cloud-main &&
          sudo docker-compose up --detach --force-recreate --build
        '
