name: 'EC2 Dockerhub-based Update'
on:
  workflow_dispatch:
  
  workflow_run:
    workflows: [Create Infrastructure]
    types:
      - completed

jobs:

 build:

  runs-on: ubuntu-latest

  steps:

  - uses: actions/checkout@v3
  - name: Get SSH key
    run:  echo "${{ secrets.CC_UNI }}" | tr -d '\r' > key.pem | chmod 600 key.pem 

  - name: Clean EC2 machine 
    run: ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@54.80.67.161 '
        sudo rm -rf * 
      '

  - name: Transfer Files to EC2
    run: |
      scp -o IdentityFile=key.pem -r ./data ec2-user@54.80.67.161:/home/ec2-user
      scp -o IdentityFile=key.pem docker-compose.dockerhub.yml ec2-user@54.80.67.161:/home/ec2-user


  - name: SSH to EC2 and Update App
    run: |
      ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@54.80.67.161 '
        sudo service docker start &&
        sudo docker-compose -f docker-compose.dockerhub.yml down && 
        sudo docker system prune &&
        sudo docker image rm -f janakaras/apartments &&
        sudo docker image rm -f janakaras/reserve &&
        sudo docker image rm -f janakaras/search &&
        sudo docker image rm -f janakaras/gateway &&
        sudo docker-compose -f docker-compose.dockerhub.yml up --detach --force-recreate --build
      '
