# This is a basic workflow that is manually triggered

name: Infrastructure Shutdown

on:
  workflow_dispatch:

jobs:
  shutdown:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
    - name: Terraform destroy
      run: terraform destroy
